### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by professor-enoqueleal** [Prophantasia/Futebolize#1]
Por favor fazer o _rename_ do repositório. 

O nome do repositório deve ser compatível com o tema escolhido.

Para o nome de repositório, seguir a convenção onde todas as letras devem ser minúsculas e as palavras separadas com **hífen** no padrão **kebab-case** https://coodesh.com/blog/candidates/dicas/convencoes-de-codificacao-do-camelcase-ao-kebab-case/

**Comment by Prophantasia** [comment]
Nome alterado conforme solicitação.
